### ISSUE TITLE
Screen scrolling down when navigating scripts

### ISSUE THREAD

**Issue by aschekatihin** [paprikka/lana-cli#7]
After update to nodejs version 6.11.1 and lana 0.0.14 it works incorrectly. When navigating scripts with up/down arrow it appends whole menu and scrolls down instead of updating (or clearing screen, not sure how it was):

![image](https://user-images.githubusercontent.com/1819406/28569970-b13cd570-7144-11e7-8a25-b8667e222ecf.png)

**Comment by paprikka** [comment]
Hm, what's the terminal client/OS/shell? Looks like cygwin/mingw on Windows.

Tested on Node 6.11 / *nix and it works fine, I presume it has something to do with terminal codes/terminal codes handled differently by your client. 

I'm currently travelling and coming back to London in the next few days. Will look at it then. In the meantime can you check if you have similar issues, say with jest test runner (or anything that utilises clear/instead of scroll)? Hope this helps in the meantime.

**Comment by aschekatihin** [comment]
Oh, terminal is kind of compex - it is windows git bash: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys) running inside of ConEmu emulation.
I have another tool that uses [blessed](https://github.com/chjj/blessed) and does full screen rendering and it works fine after update.

**Comment by aschekatihin** [comment]
I guess I fixed it for me. While investigating for more details for you I found I've actually updated **lana** package instead of **lana-cli**. When proper package was updated (to version 3.0.1) problem went away.

Thanks for your answers, please close this issue.

**Comment by paprikka** [comment]
Awesome! My guess is that the update notification showed up on your screen some time ago and you missed it. The current setting is that it shows up only once (not a big fan of nagging users with this stuff), but I'm considering every time an outdated version of the script is running.
